services:
  configuration-service:
    build:
      context: ./form-engine-backend/configuration-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${CONFIGURATION_SERVICE_CONTAINER_PORT}
    ports:
      - "${CONFIGURATION_SERVICE_HOST_PORT}:${CONFIGURATION_SERVICE_CONTAINER_PORT}"
    env_file:
      - ./form-engine-backend/env-docker/configuration-service.env
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${CONFIGURATION_SERVICE_CONTAINER_PORT}/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2m
    develop:
      watch:
        - action: rebuild
          path: ./form-engine-backend/docker-compose.watch
  service-registry:
    build:
      context: ./form-engine-backend/service-registry
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVICE_REGISTRY_CONTAINER_PORT}
    ports:
      - "${SERVICE_REGISTRY_HOST_PORT}:${SERVICE_REGISTRY_CONTAINER_PORT}"
    env_file:
      - ./form-engine-backend/env-docker/service-registry.env
    depends_on:
      configuration-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${SERVICE_REGISTRY_CONTAINER_PORT}/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2m
    develop:
      watch:
        - action: rebuild
          path: ./form-engine-backend/docker-compose.watch
  redis:
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_SERVER_HOST_PORT}:${REDIS_SERVER_CONTAINER_PORT}"
      - "${REDIS_INSIGHT_HOST_PORT}:${REDIS_INSIGHT_CONTAINER_PORT}"
    env_file:
      - ./redis.env
    volumes:
      - redis-vol:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1m
  admin-service:
    build:
      context: ./form-engine-backend/admin-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${ADMIN_SERVICE_CONTAINER_PORT}
    ports:
      - "${ADMIN_SERVICE_HOST_PORT}:${ADMIN_SERVICE_CONTAINER_PORT}"
    env_file:
      - ./form-engine-backend/env-docker/admin-service.env
    depends_on:
      configuration-service:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${ADMIN_SERVICE_CONTAINER_PORT}/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2m
    develop:
      watch:
        - action: rebuild
          path: ./form-engine-backend/docker-compose.watch
  auth-service:
    build:
      context: ./form-engine-backend/auth-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${AUTH_SERVICE_CONTAINER_PORT}
    ports:
      - "${AUTH_SERVICE_HOST_PORT}:${AUTH_SERVICE_CONTAINER_PORT}"
    env_file:
      - ./form-engine-backend/env-docker/auth-service.env
    depends_on:
      configuration-service:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${AUTH_SERVICE_CONTAINER_PORT}/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2m
    develop:
      watch:
        - action: rebuild
          path: ./form-engine-backend/docker-compose.watch
  form-data-service:
    build:
      context: ./form-engine-backend/form-data-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${FORM_DATA_SERVICE_CONTAINER_PORT}
    ports:
      - "${FORM_DATA_SERVICE_HOST_PORT}:${FORM_DATA_SERVICE_CONTAINER_PORT}"
    env_file:
      - ./form-engine-backend/env-docker/form-data-service.env
    depends_on:
      configuration-service:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      redis:
        condition: service_healthy
      form-data-cassandra-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${FORM_DATA_SERVICE_CONTAINER_PORT}/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2m
    develop:
      watch:
        - action: rebuild
          path: ./form-engine-backend/docker-compose.watch
  form-response-service:
    build:
      context: ./form-engine-backend/form-response-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${FORM_RESPONSE_SERVICE_CONTAINER_PORT}
    ports:
      - "${FORM_RESPONSE_SERVICE_HOST_PORT}:${FORM_RESPONSE_SERVICE_CONTAINER_PORT}"
    env_file:
      - ./form-engine-backend/env-docker/form-response-service.env
    depends_on:
      configuration-service:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      redis:
        condition: service_healthy
      form-response-service-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${FORM_RESPONSE_SERVICE_CONTAINER_PORT}/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2m
    develop:
      watch:
        - action: rebuild
          path: ./form-engine-backend/docker-compose.watch
  form-service:
    build:
      context: ./form-engine-backend/form-service
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${FORM_SERVICE_CONTAINER_PORT}
    ports:
      - "${FORM_SERVICE_HOST_PORT}:${FORM_SERVICE_CONTAINER_PORT}"
    env_file:
      - ./form-engine-backend/env-docker/form-service.env
    depends_on:
      configuration-service:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      redis:
        condition: service_healthy
      form-service-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${FORM_SERVICE_CONTAINER_PORT}/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2m
    develop:
      watch:
        - action: rebuild
          path: ./form-engine-backend/docker-compose.watch
  form-data-cassandra-1:
    image: cassandra:5.0
    environment:
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=256M
      - CASSANDRA_SEEDS=form-data-cassandra-1
      - CASSANDRA_CLUSTER_NAME=form-engine-cluster
      - CASSANDRA_DC=north
      - CASSANDRA_RACK=rack-1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - form-data-cassandra-1-vol:/var/lib/cassandra
    healthcheck:
        test: ["CMD-SHELL", "nodetool status | grep \"UN  $(hostname -I)\""]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 2m
  form-data-cassandra-2:
      image: cassandra:5.0
      environment:
        - MAX_HEAP_SIZE=500M
        - HEAP_NEWSIZE=256M
        - CASSANDRA_SEEDS=form-data-cassandra-1
        - CASSANDRA_CLUSTER_NAME=form-engine-cluster
        - CASSANDRA_DC=north
        - CASSANDRA_RACK=rack-2
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      volumes:
       - form-data-cassandra-2-vol:/var/lib/cassandra
      depends_on:
        form-data-cassandra-1:
          condition: service_healthy
      healthcheck:
        test: ["CMD-SHELL", "nodetool status | grep \"UN  $(hostname -I)\""]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 2m
  form-data-cassandra-3:
    image: cassandra:5.0
    environment:
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=256M
      - CASSANDRA_SEEDS=form-data-cassandra-1
      - CASSANDRA_CLUSTER_NAME=form-engine-cluster
      - CASSANDRA_DC=east
      - CASSANDRA_RACK=rack-1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - form-data-cassandra-3-vol:/var/lib/cassandra
    depends_on:
      form-data-cassandra-1:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "nodetool status | grep \"UN  $(hostname -I)\""]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 2m
  form-data-cassandra-4:
    image: cassandra:5.0
    environment:
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=256M
      - CASSANDRA_SEEDS=form-data-cassandra-1
      - CASSANDRA_CLUSTER_NAME=form-engine-cluster
      - CASSANDRA_DC=east
      - CASSANDRA_RACK=rack-2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - form-data-cassandra-4-vol:/var/lib/cassandra
    depends_on:
      form-data-cassandra-1:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "nodetool status | grep \"UN  $(hostname -I)\""]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 2m
  form-data-cassandra-5:
    image: cassandra:5.0
    environment:
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=256M
      - CASSANDRA_SEEDS=form-data-cassandra-1
      - CASSANDRA_CLUSTER_NAME=form-engine-cluster
      - CASSANDRA_DC=west
      - CASSANDRA_RACK=rack-1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - form-data-cassandra-5-vol:/var/lib/cassandra
    depends_on:
      form-data-cassandra-1:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "nodetool status | grep \"UN  $(hostname -I)\""]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 2m
  form-data-cassandra-6:
    image: cassandra:5.0
    environment:
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=256M
      - CASSANDRA_SEEDS=form-data-cassandra-1
      - CASSANDRA_CLUSTER_NAME=form-engine-cluster
      - CASSANDRA_DC=south
      - CASSANDRA_RACK=rack-1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - form-data-cassandra-6-vol:/var/lib/cassandra
    depends_on:
      form-data-cassandra-1:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "nodetool status | grep \"UN  $(hostname -I)\""]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 2m
  auth-service-postgres:
    image: postgres:18
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
    volumes:
      - auth-service-postgres-vol:/var/lib/postgresql/18/docker
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 1m
  form-service-postgres:
    image: postgres:18
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${FORM_SERVICE_POSTGRES_PASSWORD}
    volumes:
      - form-service-postgres-vol:/var/lib/postgresql/18/docker
      - ./form-engine-backend/form-service/postgres-schema-init.sql:/docker-entrypoint-initdb.d/postgres-schema-init.sql:ro
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 1m
  form-response-service-postgres:
    image: postgres:18
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${FORM_RESPONSE_SERVICE_POSTGRES_PASSWORD}
    volumes:
      - form-response-service-postgres-vol:/var/lib/postgresql/18/docker
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 1m
  client:
    build:
      context: ./form-engine-frontend
      dockerfile: Dockerfile
      args:
        - CLIENT_PORT=${CLIENT_CONTAINER_PORT}
    ports:
      - "${CLIENT_HOST_PORT}:${CLIENT_CONTAINER_PORT}"
    depends_on:
      auth-service:
        condition: service_healthy
      form-data-service:
        condition: service_healthy
      form-response-service:
        condition: service_healthy
      form-service:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./form-engine-frontend
          target: /app
        - action: rebuild
          path: ./form-engine-frontend/package.json

volumes:
  redis-vol:
  form-data-cassandra-1-vol:
  form-data-cassandra-2-vol:
  form-data-cassandra-3-vol:
  form-data-cassandra-4-vol:
  form-data-cassandra-5-vol:
  form-data-cassandra-6-vol:
  auth-service-postgres-vol:
  form-service-postgres-vol:
  form-response-service-postgres-vol: